---
version: "2"

services:
  browser:
    build:
      context: ..
      dockerfile: Dockerfile.template
    privileged: true
    ports:
      - "5011:5011"
    labels:
      io.balena.features.udev: 1
      io.balena.features.sysfs: 1
    devices:
      - /dev/dri
      - /dev/input
    environment:
      - LAUNCH_URL=https://example.com
      # - ROTATE_DISPLAY=right
      # - TOUCH_DEVICE=*Waveshare*
